//! GSLib `gamv` directional pair-set parity (M6).
//!
//! Loads fixtures generated by `gslib-vendor/generate_gamv_reference.py`:
//! - `fixtures/gamv_3d/samples.gslib` (same data as M5's skgstat fixture,
//!   reformatted for gamv).
//! - `fixtures/gamv_3d/directions.csv` — 4 directions, including omni.
//! - `fixtures/gamv_3d/dir_<name>.csv` — per-direction gamv output rows.
//!
//! For each direction, asserts:
//! - **Pair counts per lag match exactly** (set-identity tier, ignoring
//!   gamv's lag-1 self-pair bin which we don't generate).
//! - **gamma per lag matches within numerical tolerance** (numerical-
//!   equivalence tier).

use std::path::PathBuf;

use kriging_rs::variogram::{
    DirectionalConfig3D, EmpiricalEstimator, PositiveReal,
    compute_directional_variogram_3d,
};
use kriging_rs::{Coord3D, GslibDirection, PlanarDataset3D, Real};

fn fixture_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/parity_3d/fixtures/gamv_3d")
}

/// Load samples from the `.gslib` free-format file. (We could also load
/// from the equivalent skgstat_3d/samples.csv, but using the gamv-format
/// data file is closer to the actual fixture provenance.)
fn load_samples() -> PlanarDataset3D {
    let path = fixture_dir().join("samples.gslib");
    let text = std::fs::read_to_string(&path)
        .expect("samples.gslib should exist");
    let mut lines = text.lines();
    // skip header: title + n_cols + n_cols column names
    let _title = lines.next().unwrap();
    let n_cols: usize = lines.next().unwrap().trim().parse().unwrap();
    for _ in 0..n_cols {
        let _ = lines.next();
    }
    let mut coords = Vec::new();
    let mut values = Vec::new();
    for line in lines {
        let trimmed = line.trim();
        if trimmed.is_empty() {
            continue;
        }
        let parts: Vec<f64> = trimmed
            .split_whitespace()
            .map(|s| s.parse::<f64>().expect("numeric"))
            .collect();
        assert_eq!(parts.len(), 4);
        coords.push(Coord3D::new(
            parts[0] as Real,
            parts[1] as Real,
            parts[2] as Real,
        ));
        values.push(parts[3] as Real);
    }
    PlanarDataset3D::new(coords, values).unwrap()
}

#[derive(Debug)]
struct GamvDirection {
    name: String,
    azm: f64,
    atol: f64,
    bandh: f64,
    dip: f64,
    dtol: f64,
    bandv: f64,
    xlag: f64,
    xltol: f64,
    nlag: usize,
}

fn load_directions() -> Vec<GamvDirection> {
    let text = std::fs::read_to_string(fixture_dir().join("directions.csv"))
        .expect("directions.csv should exist");
    let mut out = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if i == 0 {
            continue;
        }
        let cols: Vec<&str> = line.split(',').map(|s| s.trim()).collect();
        // idx, name, azm, atol, bandh, dip, dtol, bandv, xlag, xltol, nlag
        out.push(GamvDirection {
            name: cols[1].to_string(),
            azm: cols[2].parse().unwrap(),
            atol: cols[3].parse().unwrap(),
            bandh: cols[4].parse().unwrap(),
            dip: cols[5].parse().unwrap(),
            dtol: cols[6].parse().unwrap(),
            bandv: cols[7].parse().unwrap(),
            xlag: cols[8].parse().unwrap(),
            xltol: cols[9].parse().unwrap(),
            nlag: cols[10].parse().unwrap(),
        });
    }
    out
}

#[derive(Debug, Clone, Copy)]
struct GamvRow {
    lag_index: usize,
    gamma: f64,
    n_pairs: usize,
}

fn load_direction_output(name: &str) -> Vec<GamvRow> {
    let path = fixture_dir().join(format!("dir_{name}.csv"));
    let text = std::fs::read_to_string(&path)
        .unwrap_or_else(|_| panic!("dir_{name}.csv should exist"));
    let mut out = Vec::new();
    for (i, line) in text.lines().enumerate() {
        if i == 0 {
            continue;
        }
        let cols: Vec<&str> = line.split(',').map(|s| s.trim()).collect();
        // lag_index, mean_distance, gamma, n_pairs
        out.push(GamvRow {
            lag_index: cols[0].parse().unwrap(),
            gamma: cols[2].parse().unwrap(),
            n_pairs: cols[3].parse().unwrap(),
        });
    }
    out
}

/// Build a comparison pair-list of (n_pairs, gamma) for a gamv direction.
/// Strips:
/// - lag 1 (gamv's self-pair bin; we don't generate self-pairs).
/// - trailing zero-pair lags (the lags beyond which no pair fits).
fn gamv_bins_for_comparison(rows: &[GamvRow]) -> Vec<(usize, f64)> {
    rows.iter()
        .filter(|r| r.lag_index > 1 && r.n_pairs > 0)
        .map(|r| (r.n_pairs, r.gamma))
        .collect()
}

#[test]
fn gamv_directional_pair_counts_and_gamma_match() {
    let dataset = load_samples();
    let directions = load_directions();

    // We deliberately skip the 'omni' direction in M6: gamv's omni mode
    // double-counts each pair and counts self-pairs in lag 1; the parity
    // test focuses on the three directional cases v3 §M6 requires. M5
    // already validates omnidirectional behavior against scikit-gstat.
    let directional_cases: Vec<&GamvDirection> = directions
        .iter()
        .filter(|d| d.name != "omni")
        .collect();
    assert!(
        directional_cases.len() >= 3,
        "M6 needs at least three directional cases, got {}",
        directional_cases.len(),
    );

    // Tolerance: 1e-4 relative on both f32 and f64 because the precision
    // floor is gamv's text-output format (5 decimal digits on gamma), not
    // our floating-point storage. For example, gamv writes `0.35600` for
    // a computed value of `0.35600081...`. v3's numerical-equivalence tier
    // is unreachable against this fixture; the underlying math is fine.
    let gamma_tolerance: f64 = 1e-4;

    for dir in directional_cases {
        let filter = GslibDirection {
            azm_deg: dir.azm,
            atol_deg: dir.atol,
            bandh: dir.bandh,
            dip_deg: dir.dip,
            dtol_deg: dir.dtol,
            bandv: dir.bandv,
        }
        .to_filter()
        .unwrap_or_else(|e| panic!("filter for {}: {e}", dir.name));

        let config = DirectionalConfig3D {
            xlag: PositiveReal::try_new(dir.xlag as Real).unwrap(),
            xltol: PositiveReal::try_new(dir.xltol as Real).unwrap(),
            n_lags: dir.nlag,
            estimator: EmpiricalEstimator::Classical,
        };

        let ev = compute_directional_variogram_3d(&dataset, &filter, &config)
            .unwrap_or_else(|e| panic!("variogram for {}: {e}", dir.name));

        let rows = load_direction_output(&dir.name);
        let expected = gamv_bins_for_comparison(&rows);

        assert_eq!(
            ev.n_pairs.len(),
            expected.len(),
            "direction {}: bin count mismatch (ours={}, gamv={})",
            dir.name,
            ev.n_pairs.len(),
            expected.len(),
        );

        for (i, ((ours_np, ours_g), (exp_np, exp_g))) in ev
            .n_pairs
            .iter()
            .zip(ev.semivariances.iter())
            .zip(expected.iter())
            .enumerate()
        {
            assert_eq!(
                *ours_np, *exp_np,
                "direction {}, bin {i}: pair count mismatch (ours={ours_np}, gamv={exp_np})",
                dir.name,
            );
            let ours_g = *ours_g as f64;
            let rel_err = if exp_g.abs() > 1e-12 {
                (ours_g - exp_g).abs() / exp_g.abs()
            } else {
                (ours_g - exp_g).abs()
            };
            assert!(
                rel_err < gamma_tolerance,
                "direction {}, bin {i}: gamma mismatch (ours={ours_g}, gamv={exp_g}, rel_err={rel_err:e}, tol={gamma_tolerance:e})",
                dir.name,
            );
        }
    }
}
